# Generated by Django 5.2.6 on 2025-09-15 16:47

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLogs",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("project", "Project"),
                            ("form", "Form"),
                            ("submission", "Submission"),
                            ("user", "User"),
                        ],
                        default=None,
                        max_length=30,
                        verbose_name="Resource Type",
                    ),
                ),
                ("resource_id", models.CharField(verbose_name="Resource ID")),
                ("details", models.JSONField(verbose_name="Details")),
                ("success", models.BooleanField(default=True, verbose_name="Success")),
                ("action", models.CharField(max_length=100, verbose_name="Action")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="odk_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sycosur Audit Log",
                "verbose_name_plural": "Sycosur Audit Logs",
                "db_table": "audit_logs",
            },
        ),
    ]
