# Generated by Django 5.2.8 on 2025-12-04 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditlogs",
            options={"verbose_name": "Audit Log", "verbose_name_plural": "Audit Logs"},
        ),
    ]
