# Generated by Django 5.2.8 on 2025-12-01 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("odk", "0001_initial"),
    ]

    operations = []
