# Generated by Django 5.2.8 on 2025-12-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odk", "0002_auto_20251201_1748"),
    ]

    operations = [
        migrations.CreateModel(
            name="ODKPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("view_form", "Can view ODK form"),
                    ("create_form", "Can create ODK form"),
                    ("edit_form", "Can edit ODK form"),
                    ("delete_form", "Can delete ODK form"),
                    ("view_submission", "Can view submission"),
                    ("edit_submission", "Can edit submission"),
                    ("delete_submission", "Can delete submission"),
                ],
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
