# Generated by Django 5.2.8 on 2025-12-02 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("odk", "0003_odkpermission"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ODKPermission",
        ),
    ]
