# Generated by Django 5.0.14 on 2025-07-14 17:37

from django.db import migrations, models

import core_apps.users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                max_length=60,
                null=True,
                default=None,
                verbose_name="Username",
            ),
        ),
    ]
