# Generated by Django 5.0.14 on 2025-07-22 15:26

import django.core.files.storage
from django.db import migrations, models

import core_apps.profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="/media/avatars/default_avatar.webp",
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to=core_apps.profiles.models.avatar_upload_path,
                verbose_name="Avatar",
            ),
        ),
    ]
