# Generated by Django 5.0.14 on 2025-07-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="odk_role",
            field=models.CharField(
                choices=[
                    ("data_collector", "Data Collector"),
                    ("appuser", "App User"),
                    ("manager", "Project Manager"),
                    ("administrator", "Administrator"),
                ],
                default="data_collector",
                max_length=20,
                verbose_name="ODK Role",
            ),
        ),
    ]
