# Generated by Django 5.2.8 on 2025-12-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_alter_profile_odk_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="odk_role",
            field=models.CharField(
                choices=[
                    ("data_collector", "Data Collector"),
                    ("insuco_user", "Insuco User"),
                    ("manager", "Project Manager"),
                    ("administrator", "Administrator"),
                ],
                default="manager",
                max_length=20,
                verbose_name="ODK Role",
            ),
        ),
    ]
