# Generated by Django 5.2.12 on 2026-04-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0009_alter_profile_odk_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="odk_role",
            field=models.CharField(
                choices=[
                    ("insuco_user", "Insuco User"),
                    ("manager", "Project Manager"),
                    ("administrator", "Administrator"),
                ],
                default="insuco_user",
                max_length=20,
                verbose_name="ODK Role",
            ),
        ),
    ]
