# Generated by Django 5.2.6 on 2025-09-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="archived_at",
            field=models.DateTimeField(null=True, verbose_name="Archived at"),
        ),
        migrations.AddField(
            model_name="projects",
            name="deleted",
            field=models.BooleanField(default=False, null=True, verbose_name="Deleted"),
        ),
        migrations.AddField(
            model_name="projects",
            name="deleted_at",
            field=models.DateTimeField(null=True, verbose_name="Deleted at"),
        ),
        migrations.AlterField(
            model_name="projects",
            name="archived",
            field=models.BooleanField(
                default=False, null=True, verbose_name="Archived"
            ),
        ),
    ]
