# Generated by Django 5.2.6 on 2025-10-14 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_projects_archived_at_projects_deleted_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projects",
            options={
                "ordering": ["-created_at", "name"],
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
    ]
