# Generated by Django 5.2.8 on 2025-12-01 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_projects_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projects",
            options={
                "ordering": ["-created_at", "name"],
                "permissions": [
                    ("view_project", "Can view project"),
                    ("contribute_project", "Can contribute to project"),
                    ("manage_project", "Can manage project"),
                ],
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
        migrations.DeleteModel(
            name="ProjectPermissions",
        ),
    ]
