# Generated by Django 5.2.8 on 2025-12-03 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_alter_projects_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projects",
            options={
                "ordering": ["-created_at", "name"],
                "permissions": [
                    ("access_project", "Can access project"),
                    ("archive_project", "Can archive project"),
                    ("restore_project", "Can restore project"),
                    ("manage_project", "Can manage project"),
                    ("view_form", "Can view ODK form"),
                    ("create_form", "Can create ODK form"),
                    ("edit_form", "Can edit ODK form"),
                    ("delete_form", "Can delete ODK form"),
                    ("view_submission", "Can view submission"),
                    ("edit_submission", "Can edit submission"),
                    ("delete_submission", "Can delete submission"),
                ],
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
    ]
